export const data = [
  {
    id: 1,
    name: 'Expresso Tradicional',
    desc: 'O tradicional café feito com água quente e grãos moídos',
    flags: ['TRADICIONAL'],
    src: 'src/assets/express.svg',
    value: 8.9,
    stock: 10,
  },
  {
    id: 2,
    name: 'Expresso Americano',
    desc: 'Expresso diluído, menos intenso que o tradicional',
    flags: ['TRADICIONAL'],
    src: 'src/assets/american-express.svg',
    value: 10.8,
    stock: 10,
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    desc: 'Café expresso tradicional com espuma cremosa',
    flags: ['TRADICIONAL'],
    src: 'src/assets/expresso-cremoso.svg',
    value: 9.9,
    stock: 10,
  },
  {
    id: 4,
    name: 'Expresso Gelado',
    desc: 'Bebida preparada com café expresso e cubos de gelo',
    flags: ['TRADICIONAL', 'GELADO'],
    src: 'src/assets/expresso-gelado.svg',
    value: 7.9,
    stock: 10,
  },
  {
    id: 5,
    name: 'Café com Leite',
    desc: 'Meio a meio de expresso tradicional com leite vaporizado',
    flags: ['TRADICIONAL', 'COM LEITE'],
    src: 'src/assets/cafe-com-leite.svg',
    value: 8.9,
    stock: 10,
  },
  {
    id: 6,
    name: 'Latte',
    desc: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    flags: ['TRADICIONAL', 'COM LEITE'],
    src: 'src/assets/latte.svg',
    value: 9.9,
    stock: 10,
  },
  {
    id: 7,
    name: 'Capuccino',
    desc: 'Bebida com canela feita de doses iguais de café, leite e espuma',
    flags: ['TRADICIONAL', 'COM LEITE'],
    src: 'src/assets/capuccino.svg',
    value: 8.9,
    stock: 10,
  },
  {
    id: 8,
    name: 'Macchiato',
    desc: 'Café expresso misturado com um pouco de leite quente e espuma',
    flags: ['TRADICIONAL', 'COM LEITE'],
    src: 'src/assets/macchiato.svg',
    value: 8.9,
    stock: 10,
  },
  {
    id: 9,
    name: 'Mocaccino',
    desc: 'Café expresso com calda de chocolate, pouco leite e espuma',
    flags: ['TRADICIONAL', 'COM LEITE'],
    src: 'src/assets/mochaccino.svg',
    value: 8.9,
    stock: 10,
  },
  {
    id: 10,
    name: 'Chocolate Quente',
    desc: 'Bebida feita com chocolate dissolvido no leite quente e café',
    flags: ['ESPECIAL', 'COM LEITE'],
    src: 'src/assets/chocolate-quente.svg',
    value: 8.9,
    stock: 10,
  },
  {
    id: 11,
    name: 'Cubano',
    desc: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
    flags: ['ESPECIAL', 'ALCOÓLICO', 'GELADO'],
    src: 'src/assets/cubano.svg',
    value: 8.9,
    stock: 10,
  },
  {
    id: 12,
    name: 'Havaiano',
    desc: 'Bebida adocicada preparada com café e leite de coco',
    flags: ['ESPECIAL'],
    src: 'src/assets/havaiano.svg',
    value: 8.9,
    stock: 10,
  },
  {
    id: 13,
    name: 'Árabe',
    desc: 'Bebida preparada com grãos de café árabe e especiarias',
    flags: ['ESPECIAL'],
    src: 'src/assets/arabe.svg',
    value: 9.9,
    stock: 10,
  },
  {
    id: 14,
    name: 'Irlandês',
    desc: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    flags: ['ESPECIAL', 'ALCOÓLICO'],
    src: 'src/assets/irlandes.svg',
    value: 9.9,
    stock: 10,
  },
]
